apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper-server
  name: zookeeper-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zookeeper-server
    spec:
      containers:
        - name: zookeeper-server
          image: lgomezs/zookeeper:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 2181
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
            - name: ZOO_MY_ID
              value: "1"
      imagePullSecrets:
        - name: regcred
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-server
  labels:
    app: kafka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-server
  serviceName: "kafka-server"
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: kafka-server
    spec:
      containers:
        - name: kafka-server
          image: lgomezs/kafka:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
              name: tcp
            - containerPort: 29092
              name: plaintext
            - containerPort: 9999
              name: jmx
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper-server:2181"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,PLAINTEXT_HOST://:29092"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-server:9092,PLAINTEXT_HOST://kafka-server:29092"
            - name: JMX_PORT
              value: "9999"
      imagePullSecrets:
        - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-customer-event
  name: microservice-customer-event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-customer-event
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: microservice-customer-event
    spec:
      containers:
        - name: microservice-customer-event
          image: lgomezs/customer-microservice:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PROFILE
              value: dev
      imagePullSecrets:
        - name: regcred