pipeline {

   agent {
          docker {
              image 'docker'
              args '-v /var/run/docker.sock:/var/run/docker.sock'
          }
      }

  stages {

    stage('Checkout Source') {
      steps {
        git url:'https://github.com/lgomezs/microservice-customer-kafka.git', branch:'master'
      }
    }

  stage("Build image") {
        steps {
            script {
                myapp = docker.build("customer-app","-f customer-app/Dockerfile .")
            }
        }
    }


  }

}