server:
  port: ${PORT:8080}
spring:
  application:
    name: ${APPLICATION_NAME:microservice-customer-event}
  profiles:
    active: ${PROFILE:local}
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:""}
      fail-fast: ${CONFIG_SERVER_FAIL_FAST:false}
      enabled: ${CONFIG_SERVER_ENABLED:false}
      label: ${LABEL:develop}